// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServMarkService.Data;

#nullable disable

namespace ServMarkService.Migrations
{
    [DbContext(typeof(ProductsContext))]
    partial class ProductsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ServMarkService.Models.Category", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("TypeImg")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Category", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Clothes",
                            TypeImg = "people"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Electronics",
                            TypeImg = "tech"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Furniture",
                            TypeImg = "arch"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Toys",
                            TypeImg = "any"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Others",
                            TypeImg = "animals"
                        });
                });

            modelBuilder.Entity("ServMarkService.Models.Product.Image", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("Alt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Image", (string)null);
                });

            modelBuilder.Entity("ServMarkService.Models.Product.Product", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Product", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 0,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Price = 349.0,
                            Title = "Handcrafted Metal Towels"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 0,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 724.0,
                            Title = "Fantastic Granite Shirt"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 0,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 834.0,
                            Title = "Gorgeous Soft Shoes"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 0,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 122.0,
                            Title = "Awesome Wooden Shirt"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 0,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Price = 690.0,
                            Title = "Small Frozen Ball"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 0,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 360.0,
                            Title = "Handcrafted Frozen Sausages"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 0,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 572.0,
                            Title = "Ergonomic Plastic Mouse"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 0,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 972.0,
                            Title = "Gorgeous Frozen Fish"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 0,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 547.0,
                            Title = "Gorgeous Cotton Cheese"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 0,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 806.0,
                            Title = "Fantastic Frozen Pants"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 0,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 830.0,
                            Title = "Unbranded Fresh Cheese"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 0,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 306.0,
                            Title = "Ergonomic Cotton Car"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 0,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 794.0,
                            Title = "Sleek Fresh Keyboard"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 0,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Price = 223.0,
                            Title = "Handmade Steel Hat"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 0,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 910.0,
                            Title = "Licensed Concrete Towels"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 0,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Price = 851.0,
                            Title = "Intelligent Wooden Salad"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 0,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 468.0,
                            Title = "Handmade Granite Tuna"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 0,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 842.0,
                            Title = "Unbranded Concrete Ball"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 0,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 524.0,
                            Title = "Rustic Cotton Computer"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 0,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 401.0,
                            Title = "Rustic Cotton Mouse"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 0,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 249.0,
                            Title = "Licensed Cotton Salad"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 0,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 880.0,
                            Title = "Awesome Plastic Shirt"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 0,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 663.0,
                            Title = "Handcrafted Steel Pizza"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 0,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 490.0,
                            Title = "Tasty Wooden Pizza"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 0,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 931.0,
                            Title = "Ergonomic Plastic Chicken"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 0,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 121.0,
                            Title = "Fantastic Steel Hat"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 0,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Price = 759.0,
                            Title = "Practical Wooden Keyboard"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 0,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 997.0,
                            Title = "Tasty Metal Hat"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 0,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Price = 902.0,
                            Title = "Refined Plastic Tuna"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 0,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Price = 517.0,
                            Title = "Generic Metal Cheese"
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 0,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 458.0,
                            Title = "Fantastic Concrete Hat"
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 0,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 179.0,
                            Title = "Sleek Wooden Bacon"
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 0,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 142.0,
                            Title = "Intelligent Metal Car"
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 0,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 593.0,
                            Title = "Gorgeous Plastic Soap"
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 0,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 666.0,
                            Title = "Small Fresh Table"
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 0,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 254.0,
                            Title = "Small Granite Car"
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 0,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 459.0,
                            Title = "Small Concrete Hat"
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 0,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 985.0,
                            Title = "Tasty Concrete Car"
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 0,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 740.0,
                            Title = "Ergonomic Cotton Ball"
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 0,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 754.0,
                            Title = "Intelligent Metal Car"
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 0,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 675.0,
                            Title = "Ergonomic Fresh Table"
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 0,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 412.0,
                            Title = "Sleek Soft Chicken"
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 0,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 911.0,
                            Title = "Generic Soft Chips"
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 0,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Price = 468.0,
                            Title = "Handcrafted Metal Soap"
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 0,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 994.0,
                            Title = "Ergonomic Rubber Cheese"
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 0,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 883.0,
                            Title = "Generic Metal Bike"
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 0,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 981.0,
                            Title = "Gorgeous Wooden Hat"
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 0,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 201.0,
                            Title = "Ergonomic Wooden Hat"
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 0,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 814.0,
                            Title = "Generic Metal Chair"
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 0,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 622.0,
                            Title = "Refined Wooden Car"
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 0,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 581.0,
                            Title = "Fantastic Granite Chicken"
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 0,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 392.0,
                            Title = "Tasty Metal Bacon"
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 0,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 516.0,
                            Title = "Small Plastic Bacon"
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 0,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Price = 305.0,
                            Title = "Practical Plastic Shirt"
                        },
                        new
                        {
                            Id = 55,
                            CategoryId = 0,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Price = 677.0,
                            Title = "Gorgeous Wooden Computer"
                        },
                        new
                        {
                            Id = 56,
                            CategoryId = 0,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 864.0,
                            Title = "Generic Rubber Tuna"
                        },
                        new
                        {
                            Id = 57,
                            CategoryId = 0,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 989.0,
                            Title = "Rustic Concrete Car"
                        },
                        new
                        {
                            Id = 58,
                            CategoryId = 0,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Price = 787.0,
                            Title = "Handmade Concrete Hat"
                        },
                        new
                        {
                            Id = 59,
                            CategoryId = 0,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Price = 748.0,
                            Title = "Rustic Soft Bacon"
                        },
                        new
                        {
                            Id = 60,
                            CategoryId = 0,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 905.0,
                            Title = "Small Fresh Tuna"
                        },
                        new
                        {
                            Id = 61,
                            CategoryId = 0,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 298.0,
                            Title = "Small Fresh Bacon"
                        },
                        new
                        {
                            Id = 62,
                            CategoryId = 0,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 815.0,
                            Title = "Incredible Steel Ball"
                        },
                        new
                        {
                            Id = 63,
                            CategoryId = 0,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 76.0,
                            Title = "Rustic Granite Table"
                        },
                        new
                        {
                            Id = 64,
                            CategoryId = 0,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Price = 744.0,
                            Title = "Ergonomic Plastic Pants"
                        },
                        new
                        {
                            Id = 65,
                            CategoryId = 0,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Price = 739.0,
                            Title = "Small Soft Tuna"
                        },
                        new
                        {
                            Id = 66,
                            CategoryId = 0,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 486.0,
                            Title = "Generic Granite Chair"
                        },
                        new
                        {
                            Id = 67,
                            CategoryId = 0,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 384.0,
                            Title = "Gorgeous Steel Car"
                        },
                        new
                        {
                            Id = 68,
                            CategoryId = 0,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 818.0,
                            Title = "Small Fresh Gloves"
                        },
                        new
                        {
                            Id = 69,
                            CategoryId = 0,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 34.0,
                            Title = "Rustic Frozen Soap"
                        },
                        new
                        {
                            Id = 70,
                            CategoryId = 0,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 899.0,
                            Title = "Gorgeous Soft Salad"
                        },
                        new
                        {
                            Id = 71,
                            CategoryId = 0,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 806.0,
                            Title = "Fantastic Concrete Chair"
                        },
                        new
                        {
                            Id = 72,
                            CategoryId = 0,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Price = 481.0,
                            Title = "Handmade Metal Gloves"
                        },
                        new
                        {
                            Id = 73,
                            CategoryId = 0,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 525.0,
                            Title = "Sleek Wooden Ball"
                        },
                        new
                        {
                            Id = 74,
                            CategoryId = 0,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 192.0,
                            Title = "Generic Plastic Fish"
                        },
                        new
                        {
                            Id = 75,
                            CategoryId = 0,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 98.0,
                            Title = "Unbranded Frozen Keyboard"
                        },
                        new
                        {
                            Id = 76,
                            CategoryId = 0,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 943.0,
                            Title = "Licensed Fresh Soap"
                        },
                        new
                        {
                            Id = 77,
                            CategoryId = 0,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 235.0,
                            Title = "Handmade Granite Mouse"
                        },
                        new
                        {
                            Id = 78,
                            CategoryId = 0,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 887.0,
                            Title = "Refined Steel Keyboard"
                        },
                        new
                        {
                            Id = 79,
                            CategoryId = 0,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 184.0,
                            Title = "Refined Soft Hat"
                        },
                        new
                        {
                            Id = 80,
                            CategoryId = 0,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 203.0,
                            Title = "Small Fresh Sausages"
                        },
                        new
                        {
                            Id = 81,
                            CategoryId = 0,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 331.0,
                            Title = "Handmade Cotton Tuna"
                        },
                        new
                        {
                            Id = 82,
                            CategoryId = 0,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 23.0,
                            Title = "Intelligent Granite Chair"
                        },
                        new
                        {
                            Id = 83,
                            CategoryId = 0,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Price = 947.0,
                            Title = "Handmade Concrete Table"
                        },
                        new
                        {
                            Id = 84,
                            CategoryId = 0,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 2.0,
                            Title = "Awesome Plastic Chicken"
                        },
                        new
                        {
                            Id = 85,
                            CategoryId = 0,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 112.0,
                            Title = "Ergonomic Cotton Gloves"
                        },
                        new
                        {
                            Id = 86,
                            CategoryId = 0,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 474.0,
                            Title = "Awesome Steel Gloves"
                        },
                        new
                        {
                            Id = 87,
                            CategoryId = 0,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Price = 662.0,
                            Title = "Rustic Soft Tuna"
                        },
                        new
                        {
                            Id = 88,
                            CategoryId = 0,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 571.0,
                            Title = "Handmade Wooden Chicken"
                        },
                        new
                        {
                            Id = 89,
                            CategoryId = 0,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Price = 249.0,
                            Title = "Fantastic Granite Pants"
                        },
                        new
                        {
                            Id = 90,
                            CategoryId = 0,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Price = 636.0,
                            Title = "Refined Concrete Gloves"
                        },
                        new
                        {
                            Id = 91,
                            CategoryId = 0,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 891.0,
                            Title = "Practical Wooden Gloves"
                        },
                        new
                        {
                            Id = 92,
                            CategoryId = 0,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 54.0,
                            Title = "Gorgeous Cotton Towels"
                        },
                        new
                        {
                            Id = 93,
                            CategoryId = 0,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Price = 893.0,
                            Title = "Intelligent Metal Towels"
                        },
                        new
                        {
                            Id = 94,
                            CategoryId = 0,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Price = 218.0,
                            Title = "Incredible Fresh Car"
                        },
                        new
                        {
                            Id = 95,
                            CategoryId = 0,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 525.0,
                            Title = "Unbranded Steel Sausages"
                        },
                        new
                        {
                            Id = 96,
                            CategoryId = 0,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Price = 193.0,
                            Title = "Sleek Steel Bike"
                        },
                        new
                        {
                            Id = 97,
                            CategoryId = 0,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 410.0,
                            Title = "Awesome Metal Sausages"
                        },
                        new
                        {
                            Id = 98,
                            CategoryId = 0,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 251.0,
                            Title = "Gorgeous Frozen Chips"
                        },
                        new
                        {
                            Id = 99,
                            CategoryId = 0,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 681.0,
                            Title = "Licensed Wooden Sausages"
                        },
                        new
                        {
                            Id = 100,
                            CategoryId = 0,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 415.0,
                            Title = "Ergonomic Rubber Ball"
                        },
                        new
                        {
                            Id = 101,
                            CategoryId = 0,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 264.0,
                            Title = "Handcrafted Rubber Sausages"
                        },
                        new
                        {
                            Id = 102,
                            CategoryId = 0,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 547.0,
                            Title = "Sleek Cotton Chair"
                        },
                        new
                        {
                            Id = 103,
                            CategoryId = 0,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 866.0,
                            Title = "Rustic Frozen Pants"
                        },
                        new
                        {
                            Id = 104,
                            CategoryId = 0,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 801.0,
                            Title = "Tasty Steel Car"
                        },
                        new
                        {
                            Id = 105,
                            CategoryId = 0,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 511.0,
                            Title = "Awesome Rubber Chair"
                        },
                        new
                        {
                            Id = 106,
                            CategoryId = 0,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 714.0,
                            Title = "Tasty Rubber Cheese"
                        },
                        new
                        {
                            Id = 107,
                            CategoryId = 0,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 685.0,
                            Title = "Gorgeous Cotton Computer"
                        },
                        new
                        {
                            Id = 108,
                            CategoryId = 0,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 466.0,
                            Title = "Ergonomic Soft Tuna"
                        },
                        new
                        {
                            Id = 109,
                            CategoryId = 0,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 602.0,
                            Title = "Handcrafted Wooden Gloves"
                        },
                        new
                        {
                            Id = 110,
                            CategoryId = 0,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 272.0,
                            Title = "Awesome Steel Chips"
                        },
                        new
                        {
                            Id = 111,
                            CategoryId = 0,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 227.0,
                            Title = "Tasty Granite Table"
                        },
                        new
                        {
                            Id = 112,
                            CategoryId = 0,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 345.0,
                            Title = "Practical Frozen Keyboard"
                        },
                        new
                        {
                            Id = 113,
                            CategoryId = 0,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Price = 320.0,
                            Title = "Practical Granite Pizza"
                        },
                        new
                        {
                            Id = 114,
                            CategoryId = 0,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 784.0,
                            Title = "Handmade Metal Mouse"
                        },
                        new
                        {
                            Id = 115,
                            CategoryId = 0,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 329.0,
                            Title = "Refined Wooden Car"
                        },
                        new
                        {
                            Id = 116,
                            CategoryId = 0,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 161.0,
                            Title = "Practical Wooden Bike"
                        },
                        new
                        {
                            Id = 117,
                            CategoryId = 0,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Price = 694.0,
                            Title = "Handmade Rubber Towels"
                        },
                        new
                        {
                            Id = 118,
                            CategoryId = 0,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 802.0,
                            Title = "Generic Fresh Chicken"
                        },
                        new
                        {
                            Id = 119,
                            CategoryId = 0,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 658.0,
                            Title = "Small Granite Bacon"
                        },
                        new
                        {
                            Id = 120,
                            CategoryId = 0,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 241.0,
                            Title = "Rustic Wooden Pants"
                        },
                        new
                        {
                            Id = 121,
                            CategoryId = 0,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 113.0,
                            Title = "Generic Plastic Bike"
                        },
                        new
                        {
                            Id = 122,
                            CategoryId = 0,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 297.0,
                            Title = "Rustic Rubber Towels"
                        },
                        new
                        {
                            Id = 123,
                            CategoryId = 0,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 654.0,
                            Title = "Handcrafted Metal Chips"
                        },
                        new
                        {
                            Id = 124,
                            CategoryId = 0,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 674.0,
                            Title = "Refined Soft Towels"
                        },
                        new
                        {
                            Id = 125,
                            CategoryId = 0,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Price = 838.0,
                            Title = "Generic Granite Cheese"
                        },
                        new
                        {
                            Id = 126,
                            CategoryId = 0,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 82.0,
                            Title = "Handcrafted Wooden Salad"
                        },
                        new
                        {
                            Id = 127,
                            CategoryId = 0,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Price = 535.0,
                            Title = "Generic Wooden Car"
                        },
                        new
                        {
                            Id = 128,
                            CategoryId = 0,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 488.0,
                            Title = "Incredible Steel Bike"
                        },
                        new
                        {
                            Id = 129,
                            CategoryId = 0,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 725.0,
                            Title = "Refined Wooden Sausages"
                        },
                        new
                        {
                            Id = 130,
                            CategoryId = 0,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 591.0,
                            Title = "Small Cotton Chicken"
                        },
                        new
                        {
                            Id = 131,
                            CategoryId = 0,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 319.0,
                            Title = "Small Frozen Ball"
                        },
                        new
                        {
                            Id = 132,
                            CategoryId = 0,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Price = 572.0,
                            Title = "Handcrafted Concrete Ball"
                        },
                        new
                        {
                            Id = 133,
                            CategoryId = 0,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 945.0,
                            Title = "Refined Steel Tuna"
                        },
                        new
                        {
                            Id = 134,
                            CategoryId = 0,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 933.0,
                            Title = "Intelligent Soft Fish"
                        },
                        new
                        {
                            Id = 135,
                            CategoryId = 0,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 628.0,
                            Title = "Incredible Steel Pizza"
                        },
                        new
                        {
                            Id = 136,
                            CategoryId = 0,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 61.0,
                            Title = "Gorgeous Cotton Keyboard"
                        },
                        new
                        {
                            Id = 137,
                            CategoryId = 0,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 550.0,
                            Title = "Awesome Steel Ball"
                        },
                        new
                        {
                            Id = 138,
                            CategoryId = 0,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 947.0,
                            Title = "Licensed Steel Shoes"
                        },
                        new
                        {
                            Id = 139,
                            CategoryId = 0,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Price = 1.0,
                            Title = "Practical Fresh Car"
                        },
                        new
                        {
                            Id = 140,
                            CategoryId = 0,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 583.0,
                            Title = "Gorgeous Soft Shirt"
                        },
                        new
                        {
                            Id = 141,
                            CategoryId = 0,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 835.0,
                            Title = "Practical Soft Chicken"
                        },
                        new
                        {
                            Id = 142,
                            CategoryId = 0,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 999.0,
                            Title = "Refined Wooden Car"
                        },
                        new
                        {
                            Id = 143,
                            CategoryId = 0,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 229.0,
                            Title = "Awesome Plastic Mouse"
                        },
                        new
                        {
                            Id = 144,
                            CategoryId = 0,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 761.0,
                            Title = "Gorgeous Rubber Bacon"
                        },
                        new
                        {
                            Id = 145,
                            CategoryId = 0,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Price = 640.0,
                            Title = "Fantastic Wooden Pants"
                        },
                        new
                        {
                            Id = 146,
                            CategoryId = 0,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 74.0,
                            Title = "Awesome Plastic Bike"
                        },
                        new
                        {
                            Id = 147,
                            CategoryId = 0,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 976.0,
                            Title = "Generic Cotton Fish"
                        },
                        new
                        {
                            Id = 148,
                            CategoryId = 0,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 134.0,
                            Title = "Ergonomic Concrete Keyboard"
                        },
                        new
                        {
                            Id = 149,
                            CategoryId = 0,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 831.0,
                            Title = "Licensed Frozen Ball"
                        },
                        new
                        {
                            Id = 150,
                            CategoryId = 0,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Price = 278.0,
                            Title = "Handcrafted Steel Bacon"
                        },
                        new
                        {
                            Id = 151,
                            CategoryId = 0,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 495.0,
                            Title = "Small Cotton Fish"
                        },
                        new
                        {
                            Id = 152,
                            CategoryId = 0,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 814.0,
                            Title = "Generic Plastic Salad"
                        },
                        new
                        {
                            Id = 153,
                            CategoryId = 0,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 656.0,
                            Title = "Tasty Steel Shirt"
                        },
                        new
                        {
                            Id = 154,
                            CategoryId = 0,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 177.0,
                            Title = "Ergonomic Rubber Bacon"
                        },
                        new
                        {
                            Id = 155,
                            CategoryId = 0,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 493.0,
                            Title = "Handmade Fresh Car"
                        },
                        new
                        {
                            Id = 156,
                            CategoryId = 0,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 823.0,
                            Title = "Incredible Metal Ball"
                        },
                        new
                        {
                            Id = 157,
                            CategoryId = 0,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 731.0,
                            Title = "Intelligent Concrete Bike"
                        },
                        new
                        {
                            Id = 158,
                            CategoryId = 0,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 81.0,
                            Title = "Handmade Steel Car"
                        },
                        new
                        {
                            Id = 159,
                            CategoryId = 0,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 550.0,
                            Title = "Generic Steel Hat"
                        },
                        new
                        {
                            Id = 160,
                            CategoryId = 0,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 807.0,
                            Title = "Unbranded Granite Ball"
                        },
                        new
                        {
                            Id = 161,
                            CategoryId = 0,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 798.0,
                            Title = "Licensed Metal Table"
                        },
                        new
                        {
                            Id = 162,
                            CategoryId = 0,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 632.0,
                            Title = "Handcrafted Fresh Ball"
                        },
                        new
                        {
                            Id = 163,
                            CategoryId = 0,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 527.0,
                            Title = "Practical Steel Salad"
                        },
                        new
                        {
                            Id = 164,
                            CategoryId = 0,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 2.0,
                            Title = "Small Rubber Pizza"
                        },
                        new
                        {
                            Id = 165,
                            CategoryId = 0,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 951.0,
                            Title = "Handmade Steel Cheese"
                        },
                        new
                        {
                            Id = 166,
                            CategoryId = 0,
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            Price = 804.0,
                            Title = "Generic Granite Bacon"
                        },
                        new
                        {
                            Id = 167,
                            CategoryId = 0,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 266.0,
                            Title = "Intelligent Metal Pizza"
                        },
                        new
                        {
                            Id = 168,
                            CategoryId = 0,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 369.0,
                            Title = "Intelligent Fresh Bike"
                        },
                        new
                        {
                            Id = 169,
                            CategoryId = 0,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 702.0,
                            Title = "Fantastic Concrete Chair"
                        },
                        new
                        {
                            Id = 170,
                            CategoryId = 0,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 91.0,
                            Title = "Small Fresh Soap"
                        },
                        new
                        {
                            Id = 171,
                            CategoryId = 0,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 958.0,
                            Title = "Licensed Soft Soap"
                        },
                        new
                        {
                            Id = 172,
                            CategoryId = 0,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 867.0,
                            Title = "Awesome Metal Ball"
                        },
                        new
                        {
                            Id = 173,
                            CategoryId = 0,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 626.0,
                            Title = "Incredible Soft Hat"
                        },
                        new
                        {
                            Id = 174,
                            CategoryId = 0,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 184.0,
                            Title = "Handcrafted Soft Tuna"
                        },
                        new
                        {
                            Id = 175,
                            CategoryId = 0,
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            Price = 140.0,
                            Title = "Licensed Concrete Pizza"
                        },
                        new
                        {
                            Id = 176,
                            CategoryId = 0,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 590.0,
                            Title = "Generic Soft Gloves"
                        },
                        new
                        {
                            Id = 177,
                            CategoryId = 0,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 446.0,
                            Title = "Tasty Plastic Bike"
                        },
                        new
                        {
                            Id = 178,
                            CategoryId = 0,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 16.0,
                            Title = "Licensed Rubber Towels"
                        },
                        new
                        {
                            Id = 179,
                            CategoryId = 0,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 574.0,
                            Title = "Small Frozen Fish"
                        },
                        new
                        {
                            Id = 180,
                            CategoryId = 0,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 55.0,
                            Title = "Intelligent Metal Ball"
                        },
                        new
                        {
                            Id = 181,
                            CategoryId = 0,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 792.0,
                            Title = "Practical Soft Bacon"
                        },
                        new
                        {
                            Id = 182,
                            CategoryId = 0,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 882.0,
                            Title = "Handcrafted Soft Car"
                        },
                        new
                        {
                            Id = 183,
                            CategoryId = 0,
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            Price = 901.0,
                            Title = "Generic Cotton Fish"
                        },
                        new
                        {
                            Id = 184,
                            CategoryId = 0,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 37.0,
                            Title = "Intelligent Granite Towels"
                        },
                        new
                        {
                            Id = 185,
                            CategoryId = 0,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 170.0,
                            Title = "Small Rubber Chicken"
                        },
                        new
                        {
                            Id = 186,
                            CategoryId = 0,
                            Description = "Ergonomic executive chair upholstered in bonded black leather and PVC padded seat and back for all-day comfort and support",
                            Price = 480.0,
                            Title = "Generic Fresh Sausages"
                        },
                        new
                        {
                            Id = 187,
                            CategoryId = 0,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 555.0,
                            Title = "Ergonomic Concrete Bike"
                        },
                        new
                        {
                            Id = 188,
                            CategoryId = 0,
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            Price = 800.0,
                            Title = "Generic Fresh Computer"
                        },
                        new
                        {
                            Id = 189,
                            CategoryId = 0,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 34.0,
                            Title = "Rustic Metal Pizza"
                        },
                        new
                        {
                            Id = 190,
                            CategoryId = 0,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 410.0,
                            Title = "Generic Steel Tuna"
                        },
                        new
                        {
                            Id = 191,
                            CategoryId = 0,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 521.0,
                            Title = "Licensed Frozen Shoes"
                        },
                        new
                        {
                            Id = 192,
                            CategoryId = 0,
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            Price = 588.0,
                            Title = "Ergonomic Frozen Chips"
                        },
                        new
                        {
                            Id = 193,
                            CategoryId = 0,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 937.0,
                            Title = "Tasty Fresh Pants"
                        },
                        new
                        {
                            Id = 194,
                            CategoryId = 0,
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            Price = 457.0,
                            Title = "Small Wooden Fish"
                        },
                        new
                        {
                            Id = 195,
                            CategoryId = 0,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 990.0,
                            Title = "Handmade Plastic Pants"
                        },
                        new
                        {
                            Id = 196,
                            CategoryId = 0,
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            Price = 585.0,
                            Title = "Incredible Cotton Car"
                        },
                        new
                        {
                            Id = 197,
                            CategoryId = 0,
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            Price = 216.0,
                            Title = "Rustic Concrete Chips"
                        },
                        new
                        {
                            Id = 198,
                            CategoryId = 0,
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            Price = 758.0,
                            Title = "Fantastic Concrete Cheese"
                        },
                        new
                        {
                            Id = 199,
                            CategoryId = 0,
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            Price = 820.0,
                            Title = "Fantastic Fresh Tuna"
                        },
                        new
                        {
                            Id = 200,
                            CategoryId = 0,
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            Price = 217.0,
                            Title = "Refined Frozen Fish"
                        });
                });

            modelBuilder.Entity("ServMarkService.Models.Product.Image", b =>
                {
                    b.HasOne("ServMarkService.Models.Product.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ServMarkService.Models.Product.Product", b =>
                {
                    b.HasOne("ServMarkService.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ServMarkService.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ServMarkService.Models.Product.Product", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
